version: '3'

networks:
  mapeditor-net:
    external:
      name: mapeditor-net

services:
  essim-engine:
    image: esdlmapeditoressim/essim:latest
    ports:
     - 8112:8112
    environment:
     - HTTP_SERVER_SCHEME=http
     - HTTP_SERVER_HOSTNAME=0.0.0.0
     - HTTP_SERVER_PORT=8112
     - HTTP_SERVER_PATH=essim
     - MONGODB_HOST=mongo
     - MONGODB_PORT=27017
     - GRAFANA_ADMIN_USER=admin
     - GRAFANA_ADMIN_PASSWORD=admin
     - GRAFANA_INTERNAL_URL=http://grafana:3000
     - GRAFANA_EXTERNAL_URL=http://localhost:3000
    networks:
     - mapeditor-net

  nats:
    image: esdlmapeditoressim/nats-server:latest
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222
    networks:
     - mapeditor-net


