apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
          # valueFrom:
          #   secretKeyRef:
          #     name: postgres-secret
          #     key: password
        - name: POSTGRES_USER
          value: postgres
          # valueFrom:
          #   secretKeyRef:
          #     name: postgres-secret
          #     key: user
        image: postgis/postgis:12-master
        # livenessProbe:
        #   exec:
        #     command:
        #     - pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
        #   periodSeconds: 15
        #   timeoutSeconds: 5
        name: postgres
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: postgres-storage
        - mountPath: /docker-entrypoint-initdb.d
          name: init-database
        - mountPath: /data/boundaries
          name: boundaries
      restartPolicy: Always
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-storage
      - name: init-database
        persistentVolumeClaim:
          claimName: init-database
      - name: boundaries
        persistentVolumeClaim:
          claimName: boundaries
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    app: postgres
  name: postgres
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    app: postgres
status:
  loadBalancer: {}
