apiVersion: v1
kind: ConfigMap
metadata:
  name: essim-env
data:
  {{- if .Values.essim.env }}
  {{- range $key, $value := .Values.essim.env }}
    {{ $key }}: "{{ tpl $value $ }}"
  {{- end }}
  {{- else }}
  # No environment variables defined for this environment
  {{- end }}
