apiVersion: v1
kind: ConfigMap
metadata:
  name: mapeditor-env
data:
  {{- if .Values.mapeditor.env }}
  {{- range $key, $value := .Values.mapeditor.env }}
    {{ $key }}: "{{ tpl $value $ }}"
  {{- end }}
  {{- else }}
    # No environment variables defined for this environment
  {{- end }}